# This is a basic workflow to help you get started with Actions

name: Run goodtables on each CSV

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install goodtables

    - name: check canonical_story.csv
      run: goodtables data/canonical_story.csv

    - name: check collection.csv
      run: goodtables data/collection.csv

    - name: check macomber_incipits.csv
      run: goodtables data/macomber_incipits.csv

    - name: check manuscript.csv
      run: goodtables data/manuscript.csv

    - name: check story_instance.csv
      run: goodtables data/story_instance.csv

    - name: check story_origin.csv
      run: goodtables data/story_origin.csv
