name: Validate CSVs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install goodtables

    - name: Run goodtables
      run: goodtables validate datapackage.json --json -o error_summary.json

    - name: Summarize and send slack alert
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      if: ${{ always() }}
      run: python .github/send_alerts_to_slack.py
