name: Valid CSVs

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install goodtables

    - name: Validate json
      run: python -m json.tool < datapackage.json

    - name: Run goodtables
      run: goodtables validate datapackage.json --json -o error_summary.json
      if: ${{ always() }}

    - name: Summarize and send slack alert
      env:
        SLACK_GOODTABLES_WEBHOOK: ${{ secrets.SLACK_GOODTABLES_WEBHOOK }}
        ERROR_FILE: error_summary.json
        SCHEMA_PATH: datapackage.json
        ERROR_MAX: 5
      if: ${{ always() }}
      run: python .github/goodtables_report.py

    - name: Upload error summary
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: goodtables-output.json
        path: error_summary.json

    - name: Upload error summary
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: error-summary.txt
        path: error_summary.txt
